# Generated by Django 3.1.7 on 2021-03-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0002_auto_20210304_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default='hej@email.com', max_length=254, unique=True, verbose_name='email address'),
            preserve_default=False,
        ),
    ]
